# Generated by Django 3.0.4 on 2021-06-25 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210625_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='equipo_casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='core.Club'),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='equipo_invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitado', to='core.Club'),
        ),
    ]
