# Generated by Django 3.0.4 on 2021-06-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210625_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='historia',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='mision',
            field=models.TextField(default='', null=True),
        ),
    ]
