# Generated by Django 3.0.4 on 2021-06-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210625_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuentro',
            name='divicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Divicion'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='peso',
            field=models.IntegerField(null=True),
        ),
    ]
