# Generated by Django 3.0.4 on 2021-06-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210625_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(choices=[('En', 'Entrenador'), ('Dir', 'Director'), ('Coo', 'Coordinador'), ('At', 'Atleta')], max_length=50),
        ),
    ]
